from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from dataops_factory.provenance import ProvenanceError, implementation_digest


def git(repository: Path, *arguments: str) -> None:
    subprocess.run(["git", "-C", str(repository), *arguments], check=True)


def provenance_repository(tmp_path: Path) -> Path:
    repository = tmp_path / "repository"
    (repository / "src").mkdir(parents=True)
    (repository / "tests").mkdir()
    (repository / "contracts").mkdir()
    (repository / ".gitignore").write_text("__pycache__/\n*.py[cod]\n", encoding="utf-8")
    (repository / "src" / "app.py").write_text("VALUE = 1\n", encoding="utf-8")
    (repository / "tests" / "test_app.py").write_text(
        "def test_value():\n    assert 1 == 1\n", encoding="utf-8"
    )
    (repository / "contracts" / "schema.json").write_text("{}\n", encoding="utf-8")
    git(repository, "init", "--quiet")
    git(repository, "add", ".")
    return repository


def test_digest_ignores_runtime_caches_and_changes_with_tracked_content(tmp_path: Path) -> None:
    repository = provenance_repository(tmp_path)
    baseline = implementation_digest(repository)

    cache = repository / "src" / "__pycache__"
    cache.mkdir()
    (cache / "app.cpython-311.pyc").write_bytes(b"generated bytecode")
    assert implementation_digest(repository) == baseline

    (repository / "src" / "app.py").write_text("VALUE = 2\n", encoding="utf-8")
    assert implementation_digest(repository) != baseline


def test_digest_fails_closed_for_untracked_canonical_input(tmp_path: Path) -> None:
    repository = provenance_repository(tmp_path)
    baseline = implementation_digest(repository)
    new_source = repository / "src" / "new_source.py"
    new_source.write_text("VALUE = 2\n", encoding="utf-8")

    with pytest.raises(ProvenanceError, match="untracked canonical inputs"):
        implementation_digest(repository)

    git(repository, "add", new_source.relative_to(repository).as_posix())
    assert implementation_digest(repository) != baseline


def test_digest_requires_repository_context(tmp_path: Path) -> None:
    for root in ("src", "tests", "contracts"):
        (tmp_path / root).mkdir()
    with pytest.raises(ProvenanceError, match="unable to inspect canonical"):
        implementation_digest(tmp_path)
